name: bindgen
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: ping <andre.lipke@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  quiver: '>=2.0.0 <3.0.0'
  path: '>=1.5.0 <2.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

executables:
  dart-bindgen: bindgen